
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class ErrorConfigCategory : Singleton<ErrorConfigCategory>, ILubanConfig
    {

        private readonly ErrorConfig _data;

        public ErrorConfig Data => _data;

        public ErrorConfigCategory(ByteBuf _buf)
        {
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = ErrorConfig.DeserializeErrorConfig(_buf);
			EndInit();
        }


        public string Hello => _data.Hello;
        public string Ok => _data.Ok;
        public string No => _data.No;
        
        public void ResolveRef()
        {
            _data.ResolveRef();
            EndRef();
        }

        partial void EndRef();
    }

}

