
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class ErrorConfig : Luban.BeanBase
    {
        public ErrorConfig(ByteBuf _buf) 
        {
            Hello = _buf.ReadString();
            Ok = _buf.ReadString();
            No = _buf.ReadString();

            EndInit();
        }

        public static ErrorConfig DeserializeErrorConfig(ByteBuf _buf)
        {
            return new ErrorConfig(_buf);
        }

        public readonly string Hello;
        public readonly string Ok;
        public readonly string No;
    
        public const int __ID__ = 43991882;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "hello:" + Hello + ","
            + "ok:" + Ok + ","
            + "no:" + No + ","
            + "}";
        }

        partial void EndRef();
    }

}

