
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{

    [Config]
    public partial class SkillConfigCategory : Singleton<SkillConfigCategory>, ILubanConfig
    {
        private readonly Dictionary<int, SkillConfig> _dataMap;
        private readonly List<SkillConfig> _dataList;
        
        public SkillConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, SkillConfig>();
            _dataList = new List<SkillConfig>();
            
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                SkillConfig _v;
                _v = SkillConfig.DeserializeSkillConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            EndInit();
        }

        public Dictionary<int, SkillConfig> GetAll() => _dataMap;
        public Dictionary<int, SkillConfig> DataMap => _dataMap;
        public List<SkillConfig> DataList => _dataList;

        public SkillConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);

        public SkillConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            LubanLog.Error(this,key);
            return default;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
            EndRef();
        }


        partial void EndRef();
    }

}

