
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace ET
{
    [EnableClass]
    public sealed partial class SkillConfig : Luban.BeanBase
    {
        public SkillConfig(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            CAlias = _buf.ReadString();
            CCode = _buf.ReadString();
            Name = _buf.ReadString();
            CRace = _buf.ReadString();
            Position = ExternalTypeUtil.NewVector2(vec2.Deserializevec2(_buf));
            AudioType = (CustomAudioType)_buf.ReadInt();

            EndInit();
        }

        public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
        {
            return new SkillConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;
        /// <summary>
        /// 别名
        /// </summary>
        public readonly string CAlias;
        /// <summary>
        /// 唯一ID
        /// </summary>
        public readonly string CCode;
        /// <summary>
        /// 名称
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// 种族
        /// </summary>
        public readonly string CRace;
        /// <summary>
        /// 位置
        /// </summary>
        public readonly System.Numerics.Vector2 Position;
        /// <summary>
        /// 音效类型
        /// </summary>
        public readonly CustomAudioType AudioType;
    
        public const int __ID__ = -844226349;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            EndRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "CAlias:" + CAlias + ","
            + "CCode:" + CCode + ","
            + "Name:" + Name + ","
            + "CRace:" + CRace + ","
            + "Position:" + Position + ","
            + "AudioType:" + AudioType + ","
            + "}";
        }

        partial void EndRef();
    }

}

